version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=450'
    shm_size: 1gb
    expose:
      - "5432"
    ports:
      - "6000:5432"
    volumes:
      - ../entrypoint:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: toggl
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1.8GB"

networks:
  default:
    driver: bridge
    name: decks
