# Use postgres/example user/password credentials
version: "3.1"

services:
  decks:
    expose:
      - "8085"
    build:
      context: "."
    environment:
      HTTP_PORT: "8085"
      DB_MAIN_URL: "user=root password=root dbname=toggl host=db port=6000 sslmode=disable"
      SWAGGER_URL: http://localhost:3000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.25GB"

  db:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=450'
    shm_size: 1gb
    expose:
      - "6000"
    ports:
      - "6000:6000"
    volumes:
      - ./infra/entrypoint:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: toggl
      PGPORT: 6000
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1.8GB"
  nginx:
    image: nginx:latest
    volumes:
       - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - decks
    ports:
      - "3000:80"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"
networks:
  default:
    driver: bridge